default:
  deps: [test]

dl-deps:
  cmds:
    - go get -u github.com/golang/dep/cmd/dep

update-deps:
  cmds:
    - dep ensure
    - dep ensure -update

lint:
  cmds:
    - go fmt ./server/...
    - go vet ./server/...
  silent: true

test:
  cmds:
    - go test -tags=test -race ./server/...

test-coverage:
  cmds:
    - go test -tags=test -race -coverprofile=coverage.out -covermode=atomic ./server/...

dist_all:
  cmds:
    - task: _dist
      vars: {OS: "linux", ARCH: "386", exeExt: ""}
    - task: _dist
      vars: {OS: "linux", ARCH: "amd64", exeExt: ""}

dist:
  cmds:
    - task: _dist
      vars: {OS: "{{OS}}", ARCH: "{{ARCH}}", exeExt: "{{exeExt}}"}

_dist:
  cmds:
    - GOOS={{.OS}} GOARCH={{.ARCH}} go build -o plugin{{.exeExt}} ./server
    - mkdir -p dist/
    - tar -czf dist/mattermost-cron-plugin_{{.OS}}_{{.ARCH}}.tar.gz plugin.yaml plugin
    - rm plugin

clean:
  cmds:
    - rm -r dist/
